version: '3.1'
services:
  postgres:
    networks:
      - new
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_USER=pguser
      - POSTGRES_DB=pgdb
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./sql_scripts:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      start_period: 20s
      retries: 5
  clickhouse-server:
    networks:
      - new
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    environment:
      CLICKHOUSE_USER: chuser
      CLICKHOUSE_PASSWORD: chpass
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - ./clickhouse:/var/lib/clickhouse
      - ./ch_scripts:/docker-entrypoint-initdb.d
    ulimits:
      nofile: 262144
  nats:
    networks:
      - new
    image: nats:latest
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  app:
    networks:
      - new
    build:
      context: .
      dockerfile: Dockerfile
      ports:
        - '8000:8000'
      environment:
        APP_ENV: docker
        APP_PORT: :8000

        POSTGRES_PASSWORD: pgpass
        POSTGRES_USER: pguser
        POSTGRES_DB: pgdb
        POSTGRES_HOST: postgres

        CLICKHOUSE_HOST: clickhouse-server
        CLICKHOUSE_PASSWORD: chpass
        CLICKHOUSE_USER: chuser
        CLICKHOUSE_DB: chdb
      depends_on:
        - clickhouse-server
        - redis
        - nats

networks:
  new: